export const fakeChips = [
  { id: 1, label: 'Chip 1' },
  { id: 2, label: 'Chip 2' },
  { id: 3, label: 'Chip 3' },
  { id: 4, label: 'Chip 4' },
  { id: 5, label: 'Chip 5' },
  { id: 6, label: 'Chip 6' },
  { id: 7, label: 'Chip 7' },
  { id: 8, label: 'Chip 8' },
  { id: 9, label: 'Chip 9' },
  { id: 10, label: 'Chip 10' },
  { id: 11, label: 'Chip 11' },
  { id: 12, label: 'Chip 12' },
  { id: 13, label: 'Chip 13' },
  { id: 14, label: 'Chip 14' },
  { id: 15, label: 'Chip 15' },
  { id: 16, label: 'Chip 16' },
  { id: 17, label: 'Chip 17' },
  { id: 18, label: 'Chip 18' },
  { id: 19, label: 'Chip 19' },
  { id: 20, label: 'Chip 20' },
  { id: 21, label: 'Chip 21' },
  { id: 22, label: 'Chip 22' },
  { id: 23, label: 'Chip 23' },
  { id: 24, label: 'Chip 24' },
];
